const ProponentDetails = [
  {
    id: 1,
    FullName: "AnujKumar",
    Organization: "ABCPrivateLimited",
    Email: "abcprivatelimited@gmail.com",
    FullAddress: "E-36,Sector-18,Noida,UttarPradesh",
    State: "UttarPradesh",
    Postalcode: "256301",
    LicenseID: "15869324",
    Category: "Service",
    GeneralExpereince: "5Years",
    SportSpecificExperience: "4Years",
    ProjectManagerExperience: "7Years",
    DatabaseAdminExperience: "4Years",
    CoordinatoreExperince: "3Years",
    TotalCost: "20000000",
    Duration: 3,
  },
  {
    id: 2,
    FullName: "AnkitSingh",
    Organization: "dataHiringPrivateLimited",
    Email: "datahiringproposal@datahire.com",
    FullAddress: "12D,Mumbai,Maharashtra,India",
    State: "Maharashtra",
    Postalcode: "521036",
    LicenseID: "12547836",
    Category: "Service",
    GeneralExpereince: "8Years",
    SportSpecificExperience: "6Years",
    ProjectManagerExperience: "7Yaers",
    DatabaseAdminExperience: "3Years",
    CoordinatoreExperince: "4Years",
    TotalCost: "42000000",
    Duration: 1,
  },
  {
    id: 3,
    FullName: "SushantRajput",
    Organization: "AlwaysPrivateLimited",
    Email: "Allwaysprivate@gmail.com",
    FullAddress: "12-D,Pune,Maharashtra,India",
    State: "Maharashtra",
    Postalcode: "254187",
    LicenseID: "19632584",
    Category: "Service",
    GeneralExpereince: "11Years",
    SportSpecificExperience: "4Years",
    DatabaseAdminExperience: "5Years",
    ProjectManagerExperience: "5Years",
    CoordinatoreExperince: "3Years",
    TotalCost: "35000000",
    Duration: 2,
  },
  {
    id: 4,
    FullName: "RajeevRai",
    Organization: "ARYSponsorAgency",
    Email: "ARYsponsor@aryagency.com",
    FullAddress: "34,NH8,Patiala,Punjab,India",
    State: "Punjab",
    Postalcode: "254783",
    LicenseID: "19584632",
    Category: "Service",
    GeneralExpereince: "15years",
    SportSpecificExperience: "11Years",
    ProjectManagerExperience: "9Years",
    DatabaseAdminExperience: "8Years",
    CoordinatoreExperince: "5Years",
    TotalCost: "15000000",
    Duration: 4,
  },
  {
    id: 5,
    FullName: "Ankitkumar",
    Organization: "ZenSponsorPrivateLimited",
    Email: "Zensponsor@zen.com",
    FullAddress: "12D,VakilRoad,Ludhiana,Punjab,India",
    State: "Punjab",
    Postalcode: "251630",
    LicenseID: "17854632",
    Category: "Service",
    GeneralExpereince: "7Years",
    SportSpecificExperience: "6Years",
    ProjectManagerExperience: "6Years",
    DatabaseAdminExperience: "5Years",
    CoordinatoreExperince: "4Years",
    TotalCost: "14000000",
    Duration: 2,
  },
  {
    id: 6,
    FullName: "AmbrishKumar",
    Organization: "123SportPrivateLimited",
    Email: "123Sport@gmail.com",
    FullAddress: "12,HauzKhas,NewDelhi,India",
    State: "NewDelhi",
    Postalcode: "215463",
    LicenseID: "12348749",
    Category: "Equipment",
    GeneralExpereince: "7Years",
    SportSpecificExperience: "5Years",
    ProjectManagerExperience: "4Years",
    DatabaseAdminExperience: "5Years",
    CoordinatoreExperince: "2Years",
    TotalCost: "12550000",
    Duration: 2,
    OrganizationRegisteredIn: "2017",
    TurnoverOfLastThreeYears: "9,00,00,000",
    WorkProposalsCancelledIn3Years: "2",
    BidderOfOrganization: "Owner",
  },
  {
    id: 7,
    FullName: "Vikas",
    Organization: "VikasSportsIndustry",
    Email: "vikassports@gmail.com",
    FullAddress: "12,Hisar,Haryana",
    State: "Haryana",
    Postalcode: "320145",
    LicenseID: "1902546",
    Category: "Equipment",
    GeneralExpereince: "5years",
    SportSpecificExperience: "4years",
    ProjectManagerExperience: "4Years",
    DatabaseAdminExperience: "3Years",
    CoordinatoreExperince: "3Years",
    TotalCost: "12540000",
    Duration: 2,
    OrganizationRegisteredIn: "2016",
    TurnoverOfLastThreeYears: "11,00,00,000",
    WorkProposalsCancelledIn3Years: "4",
    BidderOfOrganization: "Agent",
  },
  {
    id: 8,
    FullName: "AmitKumar",
    Organization: "ASSportmanufacturingcompany",
    Email: "ASSport@gmail.com",
    FullAddress: "12,Guna,MadhyaPradesh,India",
    State: "MadhyaPradesh",
    Postalcode: "251463",
    LicenseID: "16325846",
    Category: "Equipments",
    GeneralExpereince: "15Years",
    SportSpecificExperience: "10Yeras",
    ProjectManagerExperience: "9Years",
    DatabaseAdminExperience: "8Years",
    CoordinatoreExperince: "9Years",
    TotalCost: "10000000",
    Duration: 1,
    OrganizationRegisteredIn: "2007",
    TurnoverOfLastThreeYears: "18,00,00,000",
    WorkProposalsCancelledIn3Years: "1",
    BidderOfOrganization: "Owner",
  },
  {
    id: 9,
    FullName: "SaumyaSingh",
    Organization: "SDFGPrivateLimited",
    Email: "SDFGProposal@Sdfg.com",
    FullAddress: "sector-12,Gurugram,Haryana,India",
    State: "Haryana",
    Postalcode: "263521",
    LicenseID: "185246321",
    Category: "Equipment",
    GeneralExpereince: "14Years",
    SportSpecificExperience: "10Years",
    ProjectManagerExperience: "4Years",
    DatabaseAdminExperience: "6Years",
    CoordinatoreExperince: "3Years",
    TotalCost: "14000000",
    Duration: 3,
    OrganizationRegisteredIn: "2008",
    TurnoverOfLastThreeYears: "12,00,00,000",
    WorkProposalsCancelledIn3Years: "5",
    BidderOfOrganization: "Agent",
  },
  {
    id: 10,
    FullName: "ArchanaSharma",
    Organization: "AFGPrivateLimited",
    Email: "AFGprivateproposal@gmail.com",
    FullAddress: "14,NewRoad,patiala,Punjab,India",
    State: "Punjab",
    Postalcode: "245163",
    LicenseID: "18956234",
    Category: "Equipment",
    GeneralExpereince: "10Years",
    SportSpecificExperience: "10Years",
    ProjectManagerExperience: "5Years",
    DatabaseAdminExperience: "7Years",
    CoordinatoreExperince: "6Years",
    TotalCost: "12000000",
    Duration: 4,
    OrganizationRegisteredIn: "2012",
    TurnoverOfLastThreeYears: "3,00,00,000",
    WorkProposalsCancelledIn3Years: "0",
    BidderOfOrganization: "Owner",
  },
];

export default ProponentDetails;
