const DummyTender = [
    {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1906247" ,
        "TenderReferenceNumber":":01-23002(01)/3/2022" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service & maintanence",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " NA",
        "FeePayableTo" : " “NA”",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : " 1,30,000/- ",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : " “Secretary SAI”",
        "EmdPayableAt" : " New Delhi",
        "Title" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "WorkDescription" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "26,75,616" ,
        "ProductCategory" : "Service",
        "PublishDate " : "04.03.2022",
        "BidOpeningDate " : "04.03.2022",
        "BidSubmissionStartDate" : "11.03.2022",
        "BidSubmissionEndDate" : "26.03.2022 ",
    },
    {
        "Organisation" : "Sports Authority of Delhi",
        "TenderID" :"1906247" ,
        "TenderReferenceNumber":":01-23002(01)/3/2022" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service & maintanence",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " NA",
        "FeePayableTo" : " “NA”",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : " 1,30,000/- ",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : " “Secretary SAI”",
        "EmdPayableAt" : " New Delhi",
        "Title" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "WorkDescription" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "26,75,616" ,
        "ProductCategory" : "Service",
        "PublishDate " : "04.03.2022",
        "BidOpeningDate " : "04.03.2022",
        "BidSubmissionStartDate" : "11.03.2022",
        "BidSubmissionEndDate" : "26.03.2022 ",
    },{
        "Organisation" : "FENCING ASSOCIATION OF INDIA",
        "TenderID" :"215694" ,
        "TenderReferenceNumber":"FAI/NCOE & HPCs /Fencing equipment / 2021-22/074" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Equipment",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " 2500",
        "FeePayableTo" : "FENCING ASSOCIATION OF INDIA",
        "FeePayableAt" : "New Delhi",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "2,00,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "FENCING ASSOCIATION OF INDIA",
        "EmdPayableAt" : "New Delhi",
        "Title" : "Bidding Document for Procurement of Fencing Equipment for NCOE & HPCs " ,
        "WorkDescription" : "Bidding Document for Procurement of Fencing Equipment for NCOE & HPCs nike" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "2,50,00,000" ,
        "ProductCategory" : "Equipments",
        "PublishDate " : "13.05.2021",
        "BidOpeningDate " : "09.06.2021",
        "BidSubmissionStartDate" : "18.05.2021",
        "BidSubmissionEndDate" : "02.06.2021",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1906247" ,
        "TenderReferenceNumber":":01-23002(01)/3/2022" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service & maintanence",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " NA",
        "FeePayableTo" : " “NA”",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : " 1,30,000/- ",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : " “Secretary SAI”",
        "EmdPayableAt" : " New Delhi",
        "Title" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "WorkDescription" : "Selection of Project Management Unit for the support and maintenance of Geo-Tagging & Survey Related Projects and Services" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "26,75,616" ,
        "ProductCategory" : "Service",
        "PublishDate " : "04.03.2022",
        "BidOpeningDate " : "04.03.2022",
        "BidSubmissionStartDate" : "11.03.2022",
        "BidSubmissionEndDate" : "26.03.2022 ",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1956328" ,
        "TenderReferenceNumber":"23002/1/2022" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "Offline",
        "TenderFee" : " NA",
        "FeePayableTo" : "NA",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : " 1,75,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "SECRETARY (SAI), KHELO INDIA",
        "EmdPayableAt" : "New Delhi ",
        "Title" : "HIRING OF SPONSORSHIP AGENCY" ,
        "WorkDescription" : "HIRING OF SPONSORSHIP AGENCY" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "NA" ,
        "ProductCategory" : "Services",
        "PublishDate " : "28.02.2022",
        "BidOpeningDate " : "28.03.2022",
        "BidSubmissionStartDate" : "21.03.2022",
        "BidSubmissionEndDate" : "26.03.2022",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1956248" ,
        "TenderReferenceNumber":"01-23002(01)/2/2021" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"No",
        "PaymentMode" : "offline",
        "TenderFee" : " NA",
        "FeePayableTo" : "NA",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "6,00,000/-",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "SECRETARY, SAI (KHELO INDIA)",
        "EmdPayableAt" : "New Delhi",
        "Title" : "HIRING OF THE PRODUCTION AGENCY" ,
        "WorkDescription" : "HIRING OF THE PRODUCTION AGENCY FOR KHELO INDIA UNIVERSITY GAMES 2021"  ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "NA" ,
        "ProductCategory" : "Services",
        "PublishDate " : "19:02:2022",
        "BidOpeningDate " : "14.03.2022",
        "BidSubmissionStartDate" : "03.03.2022",
        "BidSubmissionEndDate" : "12.03.2022",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1856327" ,
        "TenderReferenceNumber":"01-23002(01)/1/2021" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"No",
        "PaymentMode" : "offline",
        "TenderFee" : " NA ",
        "FeePayableTo" : "NA",
        "FeePayableAt" : "NA",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "1,70,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : " SECRETARY, SAI (KHELO INDIA)",
        "EmdPayableAt" : "New Delhi",
        "Title" : "GEO-TAGGING OF PLAYFIELDS ON PAN-INDIA BASIS" ,
        "WorkDescription" : "”Empanelment of Agencies to execute Geo-Tagging of various playfields, field assessment, certification and similar works for SAI (Sports Authority of India) on Pan-India Basis" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "NA" ,
        "ProductCategory" : "Service",
        "PublishDate " : "11.02.2022",
        "BidOpeningDate " : "07.03.2021",
        "BidSubmissionStartDate" : "25.02.2022 ",
        "BidSubmissionEndDate" : "05.03.2022",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"1956243" ,
        "TenderReferenceNumber":"1(3)/SAI/ES/2020-21/IFB-086" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Equipment",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " 2000",
        "FeePayableTo" : "SECRETARY (SAI)",
        "FeePayableAt" : "New Delhi",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "10,00,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "SECRETARY (SAI)",
        "EmdPayableAt" : "New Delhi",
        "Title" : "PROCUREMENT OF SPORTS KITS" ,
        "WorkDescription" : "PROCUREMENT OF SPORTS KITS FOR SPORTS SPECIFIC KITS AND GENERIC KITS" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "NA" ,
        "ProductCategory" : "Kits",
        "PublishDate " : "22.04.2021",
        "BidOpeningDate " : "25.05.2021",
        "BidSubmissionStartDate" : "05.05.2021",
        "BidSubmissionEndDate" : "24.05.2021",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"2014365" ,
        "TenderReferenceNumber":"1(3)/SAI/ES/2020-21/IFB-087" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Equipment",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " 3000",
        "FeePayableTo" : "SECRETARY (SAI)",
        "FeePayableAt" : "New Delhi",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "1,80,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "SECRETARY (SAI",
        "EmdPayableAt" : "New Delhi",
        "Title" : "PROCUREMENT OF SPORTS KITS" ,
        "WorkDescription" : "PROCUREMENT OF SPORTS KITS FOR SPORT KITS AND GENERIC KITS FOR THANG-TA,Gatka,Kalarippayattu,Mallakhamb,Yogasana " ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "NA" ,
        "ProductCategory" : "Equipments",
        "PublishDate" : "22.04.2021",
        "BidOpeningDate " : "25.05.2021",
        "BidSubmissionStartDate" : "05.05.2021",
        "BidSubmissionEndDate" : "24.05.2021",
        },
        
        {
        "Organisation" : "Sports Authority of India",
        "TenderID" :"2105634" ,
        "TenderReferenceNumber":"18-5/SAI/FI/MINI MARATHON/2021" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Service",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " 500",
        "FeePayableTo" : "SECRETARY (SAI",
        "FeePayableAt" : "New Delhi",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "1,70,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "SECRETARY (SAI",
        "EmdPayableAt" : "New Delhi",
        "Title" : "HIRING OF EVENT MANAGEMENT" ,
        "WorkDescription" : "HIRING OF EVENT MANAGEMENT FOR FIT INDIA MINI-MARATHON" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "1,20,00,000" ,
        "ProductCategory" : "Services",
        "PublishDate " : "9th Feb 2021",
        "BidOpeningDate " : "18th February 2021",
        "BidSubmissionStartDate" : "12thFebruary 2021",
        "BidSubmissionEndDate" : "16thFebruary 2021",
        },
        
        {
        "Organisation" : "FENCING ASSOCIATION OF INDIA ",
        "TenderID" :"2156348" ,
        "TenderReferenceNumber":"FAI/NCOE & HPCs /Fencing equipment / 2021-22/071" ,
        "TenderType" :"Open tender" ,
        "TenderCategory" : "Equipment",
        "GeneralTechnicalEvaluationAllowed" :"yes",
        "ItemwiseTechnicalEvaluationAllowed" :"yes",
        "PaymentMode" : "offline",
        "TenderFee" : " 1500",
        "FeePayableTo" : "Fencing Association of India ",
        "FeePayableAt" : "New Delhi",
        "TenderFeeExemptionAllowed" : "No",
        "EmdAmount" : "2,00,000",
        "EmdFeeType" : "Offline",
        "EmdPayableTo" : "Fencing Association of India",
        "EmdPayableAt" : "New Delhi",
        "Title" : "Bidding Documentfor Procurement of Fencing Equipment for NCOE & HPCs",
        "WorkDescription" : "Bidding Documentfor Procurement of Fencing Equipment for NCOE & HPCs" ,
        "PreQualification" : "Please refer tender documents",
        "IndependentExternalRemarks" : " No" ,
        "TenderValue" : "4,50,00,000" ,
        "ProductCategory" : "Equipment",
        "PublishDate " : "13.05.2021",
        "BidOpeningDate " : "18.06.2021",
        "BidSubmissionStartDate" : "18.05.2021",
        "BidSubmissionEndDate" : "13.06.2021",
        }
]

export default DummyTender;